[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
nom = "7.1.1"
petgraph = "0.6.2"
<<<<<<< HEAD
rayon = "1.6.1"
=======
regex = "1.7.0"
>>>>>>> f211b7c19c8ed94d84133c4e97012c6d3232165b
